### ISSUE TITLE
cmd + a followed by delete has no effect when `showMask` is false

### ISSUE THREAD

**Issue by shadymoses** [carrickjason/react-use-mask#5]
If you type in a any value, then select all in the field (cmd + a) and try to delete, nothing happens. Sometimes it will delete the second time you hit delete.

**Comment by carrickjason** [comment]
Hey @shadymoses, can you share how you're using the hook?  I haven't been able to dupe but I don't have all of the use cases built out yet.

**Comment by shadymoses** [comment]
I was using it for a date field, exactly like the example in the README. Also, I cloned the repo, installed node modules and ran `npm run storybook` to make sure I wasn't insane. Also found it happening there for the date field example.

**Comment by carrickjason** [comment]
Interesting, I cmd + a was working for me on storybook

**Comment by shadymoses** [comment]
cmd + a works to select all. The problem I found was typing `delete` after selecting. It flashed blue to white for a second, but kept the exact same value. Deleting all is working in storybook for you?

**Comment by shadymoses** [comment]
Checking again. I wish I could upload screen recordings here.

**Comment by carrickjason** [comment]
Yeah, sorry. cmd + a and delete works as expected for me

**Comment by carrickjason** [comment]
I was finally able to reproduce. This seems to happen when `showMask` is false.
